name = 'Hugo Serif'
license = 'MIT'
licenselink = 'https://github.com/zerostaticthemes/hugo-serif-theme/blob/master/LICENSE'
description = 'Serif is an advanced multi page theme for Hugo. It contains multiple content types for a typical business website. The theme is fully responsive, blazing fast and artfully illustrated.'

homepage = 'https://github.com/Pechli-Lab'
demosite = 'https://posim.netlify.app/'

tags = ['responsive','personal','company','multipage','light','bootstrap','zerostatic']
features = ['bootstrap','responsive','scss','google analytics','netlify']

[author]
  name = 'Robert Austin'
  homepage = 'https://posim.netlify.app/'
